# Generated by Django 3.2.5 on 2021-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0002_auto_20210717_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='prices',
            field=models.ManyToManyField(blank=True, to='app_2.Prices'),
        ),
    ]
