# Generated by Django 3.2.5 on 2021-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0003_alter_company_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(choices=[('ACP', 'ASSECO'), ('ALE', 'ALLEGRO'), ('PZU', 'PZU')], max_length=10),
        ),
    ]
