# Generated by Django 3.2.5 on 2021-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0005_auto_20210721_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(choices=[('ACP', 'ASSECO'), ('PKO', 'PKOBP'), ('PZU', 'PZU')], max_length=10),
        ),
    ]
